## Contoh Numpy

In [2]:
import numpy as np
a = np.arange (15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

# Membuat Array

In [11]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [14]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [15]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
c = np.array( [ [1, 2],[3, 4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [17]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones( (2,3,4), dtype=np.int16 ) # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [20]:
np.empty( (2,3) ) # unintialized , output may vary

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [21]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [22]:
np.arange(0,2,0.3) # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [23]:
from numpy import pi
np.linspace(0,2,9) #9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
x = np.linspace(0,2*pi,100) #useful to evaluate function at lots of pints
f = np.sin(x)

# Menampilkan Array

In [25]:
a = np.arange(6) #1d array
print(a)

[0 1 2 3 4 5]


In [26]:
b = np.arange(12).reshape(4,3) # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [28]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [29]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [30]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# Operasi-operasi Dasar pada Numpy

In [33]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [34]:
c = a-b
c

array([20, 29, 38, 47])

In [35]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [36]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [37]:
a<35

array([ True,  True, False, False])

In [38]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A*B # elementwise product

array([[2, 0],
       [0, 4]])

In [39]:
A.dot(B) # matrix product

array([[5, 4],
       [3, 4]])

In [40]:
np.dot(A, B) # another matrix product

array([[5, 4],
       [3, 4]])

In [41]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [42]:
b += a
b

array([[3.83155926, 3.43611868, 3.98753812],
       [3.82777747, 3.46094614, 3.93705369]])

In [43]:
a =+ b # b is not automatically converted to integer type Traceback (most recent call last):

In [44]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [45]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [46]:
c.dtype.name

'float64'

In [48]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [49]:
d.dtype.name

'complex128'

In [50]:
a = np.random.random((2,3))
a

array([[0.06583551, 0.42418872, 0.11668938],
       [0.33481887, 0.65108937, 0.46229079]])

In [51]:
a.sum()

2.0549126497733177

In [52]:
a.min()

0.06583551297379564

In [53]:
a.max()

0.6510893743577885

In [54]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
b.sum(axis=0) # sum of each column

array([12, 15, 18, 21])

In [56]:
b.min(axis=1) # min of each row

array([0, 4, 8])

In [57]:
b.cumsum(axis=1) #cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

# Fungsi Universal

In [58]:
B = np.arange(3)
B

array([0, 1, 2])

In [59]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [60]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [62]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

# Indexing, Slicing and Iterating

In [63]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [64]:
a[2]

8

In [65]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [66]:
a[:6:2] = -1000 #equivalent to a[0:6:2] = 1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [72]:
a[ : :-1] # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [73]:
for i in a:
...    print(i**(1/3.))
...

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\Users\LENOVO\AppData\Local\Temp/ipykernel_12072/3203828144.py:2: RuntimeWarning: invalid value encountered in power
  print(i**(1/3.))


In [75]:
def f(x,y):
...    return 10*x+y
...
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [76]:
b[2,3]

23

In [77]:
b[0:5, 1] # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [78]:
b[ : ,1] # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [79]:
b[1:3, : ] # each column  in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [80]:
b[-1] # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [93]:
c = np.array( [[[ 0, 1 , 2], # a 3D array (two stacked 2D arrays)
...             [ 10, 12, 13],
...             [100, 101, 102],
...             [110, 112, 113]]])
c.shape

(1, 4, 3)

In [100]:
c,[1,...] # same as c[1,:,:] or c[1]

(array([[[  0,   1,   2],
         [ 10,  12,  13],
         [100, 101, 102],
         [110, 112, 113]]]),
 [1, Ellipsis])

In [101]:
c,[2,...] # same as c[:,:,2]

(array([[[  0,   1,   2],
         [ 10,  12,  13],
         [100, 101, 102],
         [110, 112, 113]]]),
 [2, Ellipsis])

In [102]:
for row in b:
...    print(row)
...

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [103]:
for element in b.flat:
...    print(element)
...

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Mengubah Bentuk Sebuah Array

In [104]:
a = np.floor(10*np.random.random((3,4)))
a

array([[1., 8., 9., 1.],
       [2., 4., 8., 1.],
       [3., 3., 3., 2.]])

In [105]:
a.shape

(3, 4)

In [106]:
a.ravel() # returns the array , flattend

array([1., 8., 9., 1., 2., 4., 8., 1., 3., 3., 3., 2.])

In [107]:
a.reshape(6,2) #returns the array , transposed

array([[1., 8.],
       [9., 1.],
       [2., 4.],
       [8., 1.],
       [3., 3.],
       [3., 2.]])

In [108]:
a.T.shape

(4, 3)

In [109]:
a.shape

(3, 4)

In [110]:
a

array([[1., 8., 9., 1.],
       [2., 4., 8., 1.],
       [3., 3., 3., 2.]])

In [111]:
a.resize((2,6))
a

array([[1., 8., 9., 1., 2., 4.],
       [8., 1., 3., 3., 3., 2.]])

In [112]:
a.reshape(3,-1)

array([[1., 8., 9., 1.],
       [2., 4., 8., 1.],
       [3., 3., 3., 2.]])

# Menumpuk bersama array yang berbeda

In [113]:
a = np.floor(10*np.random.random((2,2)))
a

array([[4., 6.],
       [6., 3.]])

In [114]:
b = np.floor(10*np.random.random((2,2)))
b

array([[8., 0.],
       [2., 6.]])

In [115]:
np.vstack((a,b))

array([[4., 6.],
       [6., 3.],
       [8., 0.],
       [2., 6.]])

In [116]:
np.hstack((a,b))

array([[4., 6., 8., 0.],
       [6., 3., 2., 6.]])

In [126]:
from numpy import newaxis
np.column_stack((a,b))

array([[4., 2.],
       [2., 8.]])

In [127]:
a = np.array([4.,2.])
b = np.array([2.,8.])
a[:,newaxis] # This allows to have a 2D columns vector

array([[4.],
       [2.]])

In [130]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 2.],
       [2., 8.]])

In [131]:
np.vstack((a[:,newaxis],b[:,newaxis])) # The behavior of vstack is different ]

array([[4.],
       [2.],
       [2.],
       [8.]])

In [132]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

# Memecah Array Menjadi Beberapa Bagian yang Lebih Kecil 

In [133]:
a = np.floor(10*np.random.random((2,12)))
a

array([[9., 8., 5., 5., 7., 2., 4., 6., 5., 0., 9., 2.],
       [1., 3., 6., 4., 0., 8., 4., 9., 1., 0., 9., 4.]])

In [134]:
np.hsplit(a,3) #split a into 3

[array([[9., 8., 5., 5.],
        [1., 3., 6., 4.]]),
 array([[7., 2., 4., 6.],
        [0., 8., 4., 9.]]),
 array([[5., 0., 9., 2.],
        [1., 0., 9., 4.]])]

In [135]:
np.hsplit(a,(3,4)) # split a after the third and the fourth  column 

[array([[9., 8., 5.],
        [1., 3., 6.]]),
 array([[5.],
        [4.]]),
 array([[7., 2., 4., 6., 5., 0., 9., 2.],
        [0., 8., 4., 9., 1., 0., 9., 4.]])]

# Menyalin dan Menampilkan

- Jangan Menyalin Semua

In [136]:
a = np.arange(12)
b = a # no new objects is created
b is a # a and b are two names for the same ndarray object  True
b.shape = 3,4 # changes the shape of a
a.shape

(3, 4)

In [137]:
def f(x):
...    print(id(x))
...

In [138]:
id(a) # id is a unique identifier of an object

2124720608528

In [139]:
f(a)

2124720608528


- Lihat atau Saling Dangkal

In [141]:
c = a.view()
c is a

False

In [142]:
c.base is a # c is a view of the data owned by a True
c.flags.owndata

False

In [143]:
c.shape = 2,6 # a's shape doesn't change
a.shape

(3, 4)

In [144]:
c[0,4] = 1234 # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [145]:
s = a[ : , 1:3] # spaces added for clarity; could also be written "s = a[:,1,:3]"
s[:] = 10 # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

- Deep Copy

In [146]:
d = a.copy() # a new array object with new data is created
d is a

False

In [147]:
d.base is a #d doesn't share anything with a

False

In [148]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

# Aljabar Linier

In [149]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [150]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [151]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [152]:
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
u

array([[1., 0.],
       [0., 1.]])

In [15]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
print(j)

[[ 0. -1.]
 [ 1.  0.]]


In [9]:
np.dot(j, j) 

array([[-1.,  0.],
       [ 0., -1.]])

In [27]:
import numpy as np
y = np.array([[5.], [7.]])
print(y)

[[5.]
 [7.]]


In [33]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
np.linalg.solve(a, y)

[[1. 2.]
 [3. 4.]]


array([[-3.],
       [ 4.]])

In [34]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

# Automatic Reshaping

In [6]:
a = np.arange(30)
a.shape = 2,-1,3 # -1 means "whatever is needed"
a.shape = (2, 5, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

# Penumpukan Vektor

In [9]:
import numpy as np
x = np.arange(0,10,2)
print(x)

[0 2 4 6 8]


In [10]:
import numpy as np
y = np.arange(5)
print(y)

[0 1 2 3 4]


In [11]:
import numpy as np
m = np.vstack([x,y])
print(m)

[[0 2 4 6 8]
 [0 1 2 3 4]]


In [12]:
import numpy as np
xy = np.hstack([x,y])
print(xy)

[0 2 4 6 8 0 1 2 3 4]
